# Generated by Django 5.1.5 on 2026-02-17 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Konferentsiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255)),
                ('data_nachala', models.DateField()),
                ('data_okonchaniya', models.DateField()),
                ('status', models.CharField(choices=[('планируется', 'Планируется'), ('идет', 'Идет'), ('завершена', 'Завершена'), ('отменена', 'Отменена')], max_length=50)),
            ],
            options={
                'db_table': 'konferentsiya',
                'ordering': ['-data_nachala'],
            },
        ),
        migrations.CreateModel(
            name='Prozhivanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(default='Проживание', max_length=255)),
                ('kategoriya_nomerov', models.CharField(blank=True, max_length=100)),
                ('stoimost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vmestimost', models.PositiveIntegerField(default=1)),
                ('mesta_zanyaty', models.PositiveIntegerField(default=0)),
                ('mesta_svobodnye', models.PositiveIntegerField(default=0)),
                ('turbaza_nazvanie', models.CharField(blank=True, max_length=255)),
                ('kolvo_domikov', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'prozhivanie',
            },
        ),
        migrations.CreateModel(
            name='Sekciya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, unique=True)),
                ('opisanie', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'sekciya',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesto_vstrechi', models.CharField(max_length=255)),
                ('vmestimost', models.PositiveIntegerField()),
                ('tip_transfera', models.CharField(choices=[('автобус', 'Автобус'), ('маршрутка', 'Маршрутка'), ('такси', 'Такси'), ('индивидуально', 'Индивидуально')], max_length=50)),
                ('mesta_zanyaty', models.PositiveIntegerField(default=0)),
                ('mesta_svobodnye', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'transfer',
            },
        ),
        migrations.CreateModel(
            name='Doklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(default='Не выступает', max_length=255)),
                ('status_doklada', models.CharField(choices=[('на рассмотрении', 'На рассмотрении'), ('принят', 'Принят'), ('отклонен', 'Отклонен'), ('отложен', 'Отложен')], default='на рассмотрении', max_length=50)),
                ('data_podachi', models.DateTimeField(auto_now_add=True)),
                ('vystupaet', models.BooleanField(default=True)),
                ('konferentsiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.konferentsiya')),
            ],
            options={
                'db_table': 'doklad',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255)),
                ('opisanie', models.TextField(blank=True)),
                ('data_sozdaniya', models.DateTimeField(auto_now_add=True)),
                ('konferentsiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.konferentsiya')),
            ],
            options={
                'db_table': 'program',
            },
        ),
        migrations.CreateModel(
            name='Uchastnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiya', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('otchestvo', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('organizatsiya', models.CharField(blank=True, max_length=255)),
                ('gorod', models.CharField(blank=True, max_length=100)),
                ('doljnost', models.CharField(blank=True, max_length=100)),
                ('uchenaya_stepen', models.CharField(blank=True, max_length=100)),
                ('status_uchastnika', models.CharField(choices=[('зарегистрирован', 'Зарегистрирован'), ('подтвердил участие', 'Подтвердил участие'), ('отказался', 'Отказался'), ('оплатил', 'Оплатил'), ('не оплатил', 'Не оплатил')], default='зарегистрирован', max_length=50)),
                ('kommentarii', models.TextField(blank=True)),
                ('nuzhen_transfer', models.BooleanField(default=False)),
                ('konferentsiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.konferentsiya')),
                ('prozhivanie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.prozhivanie')),
                ('sektsiya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sekciya')),
            ],
            options={
                'db_table': 'uchastnik',
            },
        ),
        migrations.CreateModel(
            name='Programma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vremya_nachala', models.DateTimeField()),
                ('vremya_okonchaniya', models.DateTimeField()),
                ('nomer_v_programme', models.PositiveIntegerField(default=1)),
                ('ne_vystupaet', models.BooleanField(default=False)),
                ('doklad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doklad')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.program')),
                ('sekciya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sekciya')),
                ('uchastnik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.uchastnik')),
            ],
            options={
                'db_table': 'programma',
                'ordering': ['vremya_nachala'],
            },
        ),
        migrations.CreateModel(
            name='Otkaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prichina', models.TextField(blank=True)),
                ('status_otkaza', models.CharField(choices=[('запланирован', 'Запланирован'), ('подтвержден', 'Подтвержден')], default='запланирован', max_length=50)),
                ('doklad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doklad')),
                ('konferentsiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.konferentsiya')),
                ('uchastnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uchastnik')),
            ],
            options={
                'db_table': 'otkaz',
            },
        ),
        migrations.AddField(
            model_name='doklad',
            name='uchastnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uchastnik'),
        ),
        migrations.CreateModel(
            name='ProzhivanieTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prozhivanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prozhivanie')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transfer')),
            ],
            options={
                'db_table': 'prozhivanie_transfer',
                'unique_together': {('prozhivanie', 'transfer')},
            },
        ),
        migrations.CreateModel(
            name='UchastnikTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pribitye', models.DateTimeField(blank=True, null=True)),
                ('otpravlenie', models.DateTimeField(blank=True, null=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transfer')),
                ('uchastnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uchastnik')),
            ],
            options={
                'db_table': 'uchastnik_transfer',
                'unique_together': {('uchastnik', 'transfer')},
            },
        ),
    ]
