# Generated by Django 5.1.5 on 2026-02-17 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailShablon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=100)),
                ('tema', models.CharField(max_length=255)),
                ('tekst', models.TextField()),
                ('tip', models.CharField(choices=[('подтверждение', 'Подтверждение регистрации'), ('programma', 'Изменение программы'), ('platezh', 'Подтверждение оплаты'), ('napominanie', 'Напоминание')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'email_shablon',
            },
        ),
        migrations.CreateModel(
            name='Konferentsiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255)),
                ('data_nachala', models.DateField()),
                ('data_okonchaniya', models.DateField()),
                ('status', models.CharField(choices=[('планируется', 'Планируется'), ('идет', 'Идет'), ('завершена', 'Завершена'), ('отменена', 'Отменена')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'konferentsiya',
                'ordering': ['-data_nachala'],
            },
        ),
        migrations.CreateModel(
            name='Prozhivanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(default='Проживание', max_length=255)),
                ('kategoriya_nomerov', models.CharField(blank=True, max_length=100)),
                ('stoimost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vmestimost', models.PositiveIntegerField(default=1)),
                ('mesta_zanyaty', models.PositiveIntegerField(default=0)),
                ('mesta_svobodnye', models.PositiveIntegerField(default=0)),
                ('turbaza_nazvanie', models.CharField(blank=True, max_length=255)),
                ('kolvo_domikov', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'prozhivanie',
            },
        ),
        migrations.CreateModel(
            name='Sekciya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, unique=True)),
                ('opisanie', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sekciya',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesto_vstrechi', models.CharField(max_length=255)),
                ('vmestimost', models.PositiveIntegerField()),
                ('tip_transfera', models.CharField(choices=[('автобус', 'Автобус'), ('маршрутка', 'Маршрутка'), ('такси', 'Такси'), ('индивидуально', 'Индивидуально')], max_length=50)),
                ('mesta_zanyaty', models.PositiveIntegerField(default=0)),
                ('mesta_svobodnye', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transfer',
            },
        ),
        migrations.CreateModel(
            name='Doklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(default='Не выступает', max_length=255)),
                ('status_doklada', models.CharField(choices=[('на рассмотрении', 'На рассмотрении'), ('принят', 'Принят'), ('отклонен', 'Отклонен'), ('отложен', 'Отложен')], default='на рассмотрении', max_length=50)),
                ('data_podachi', models.DateTimeField(auto_now_add=True)),
                ('vystupaet', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('konferentsiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.konferentsiya')),
            ],
            options={
                'db_table': 'doklad',
            },
        ),
        migrations.CreateModel(
            name='ProfilPolzovatelya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Администратор'), ('organizer', 'Организатор'), ('viewer', 'Наблюдатель')], default='viewer', max_length=50)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('konferentsii', models.ManyToManyField(blank=True, to='core.konferentsiya')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profil_polzovatelya',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255)),
                ('opisanie', models.TextField(blank=True)),
                ('data_sozdaniya', models.DateTimeField(auto_now_add=True)),
                ('konferentsiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.konferentsiya')),
            ],
            options={
                'db_table': 'program',
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=100)),
                ('stoimost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opisanie', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('konferentsiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.konferentsiya')),
            ],
            options={
                'db_table': 'tarif',
                'unique_together': {('konferentsiya', 'nazvanie')},
            },
        ),
        migrations.CreateModel(
            name='Uchastnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiya', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('otchestvo', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('organizatsiya', models.CharField(blank=True, max_length=255)),
                ('gorod', models.CharField(blank=True, max_length=100)),
                ('doljnost', models.CharField(blank=True, max_length=100)),
                ('uchenaya_stepen', models.CharField(blank=True, max_length=100)),
                ('status_uchastnika', models.CharField(choices=[('зарегистрирован', 'Зарегистрирован'), ('подтвердил участие', 'Подтвердил участие'), ('отказался', 'Отказался'), ('оплатил', 'Оплатил'), ('не оплатил', 'Не оплатил')], default='зарегистрирован', max_length=50)),
                ('kommentarii', models.TextField(blank=True)),
                ('nuzhen_transfer', models.BooleanField(default=False)),
                ('oplata_polnaya', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('konferentsiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.konferentsiya')),
                ('sektsiya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sekciya')),
                ('tarif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tarif')),
            ],
            options={
                'db_table': 'uchastnik',
            },
        ),
        migrations.CreateModel(
            name='Schet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.CharField(max_length=50, unique=True)),
                ('data_vystavleniya', models.DateTimeField(auto_now_add=True)),
                ('summa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('выставлен', 'Выставлен'), ('оплачен', 'Оплачен'), ('аннулирован', 'Аннулирован')], default='выставлен', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uchastnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uchastnik')),
            ],
            options={
                'db_table': 'schet',
                'ordering': ['-data_vystavleniya'],
            },
        ),
        migrations.CreateModel(
            name='Programma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vremya_nachala', models.DateTimeField()),
                ('vremya_okonchaniya', models.DateTimeField()),
                ('nomer_v_programme', models.PositiveIntegerField(default=1)),
                ('ne_vystupaet', models.BooleanField(default=False)),
                ('pomeshchenie', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doklad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doklad')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.program')),
                ('sekciya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sekciya')),
                ('uchastnik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.uchastnik')),
            ],
            options={
                'db_table': 'programma',
                'ordering': ['vremya_nachala'],
            },
        ),
        migrations.CreateModel(
            name='Platezh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_platezha', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ожидаемый', 'Ожидаемый'), ('подтверждён', 'Подтверждён'), ('возврат', 'Возврат')], default='ожидаемый', max_length=50)),
                ('kommentarii', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uchastnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uchastnik')),
            ],
            options={
                'db_table': 'platezh',
                'ordering': ['-data_platezha'],
            },
        ),
        migrations.CreateModel(
            name='Otkaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prichina', models.TextField(blank=True)),
                ('status_otkaza', models.CharField(choices=[('запланирован', 'Запланирован'), ('подтвержден', 'Подтвержден')], default='запланирован', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doklad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doklad')),
                ('konferentsiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.konferentsiya')),
                ('uchastnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uchastnik')),
            ],
            options={
                'db_table': 'otkaz',
            },
        ),
        migrations.AddField(
            model_name='doklad',
            name='uchastnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uchastnik'),
        ),
        migrations.CreateModel(
            name='UvedomlenieLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('tema', models.CharField(max_length=255)),
                ('data_otpravki', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('отправлено', 'Отправлено'), ('ошибка', 'Ошибка'), ('открыто', 'Открыто')], max_length=50)),
                ('uchastnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uchastnik')),
            ],
            options={
                'db_table': 'uvedomlenie_log',
                'ordering': ['-data_otpravki'],
            },
        ),
        migrations.CreateModel(
            name='ProzhivanieTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prozhivanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prozhivanie')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transfer')),
            ],
            options={
                'db_table': 'prozhivanie_transfer',
                'unique_together': {('prozhivanie', 'transfer')},
            },
        ),
        migrations.CreateModel(
            name='UchastnikProzhivanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zaseleniya', models.DateField(blank=True, null=True)),
                ('data_vyseleniya', models.DateField(blank=True, null=True)),
                ('nomer_komnaty', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prozhivanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prozhivanie')),
                ('uchastnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uchastnik')),
            ],
            options={
                'db_table': 'uchastnik_prozhivanie',
                'unique_together': {('uchastnik', 'prozhivanie')},
            },
        ),
        migrations.CreateModel(
            name='UchastnikTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pribitye', models.DateTimeField(blank=True, null=True)),
                ('otpravlenie', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transfer')),
                ('uchastnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uchastnik')),
            ],
            options={
                'db_table': 'uchastnik_transfer',
                'unique_together': {('uchastnik', 'transfer')},
            },
        ),
    ]
