# Generated by Django 5.1.5 on 2026-02-20 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sekciya',
            name='konferentsiya',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sekciyas', to='core.konferentsiya'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sekciya',
            name='nazvanie',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='sekciya',
            unique_together={('nazvanie', 'konferentsiya')},
        ),
    ]
