# Generated by Django 5.1.5 on 2026-02-20 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sekciya_options_sekciya_konferentsiya_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='konferentsiya',
            name='mesto_provedeniya',
            field=models.CharField(choices=[('gorod', 'Город (гостиница)'), ('turbase', 'Турбаза'), ('smeshanno', 'Смешанно')], default='gorod', max_length=50, verbose_name='Место проведения'),
        ),
        migrations.AddField(
            model_name='konferentsiya',
            name='trebuetsya_prozhivanie',
            field=models.BooleanField(default=False, help_text='Если отмечено, для конференции организуется проживание', verbose_name='Требуется проживание'),
        ),
        migrations.AddField(
            model_name='prozhivanie',
            name='konferentsiya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prozhivaniya', to='core.konferentsiya', verbose_name='Конференция'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='konferentsiya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='core.konferentsiya', verbose_name='Конференция'),
        ),
        migrations.AddField(
            model_name='uchastnik',
            name='data_vyseleniya',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выезда'),
        ),
        migrations.AddField(
            model_name='uchastnik',
            name='data_zaseleniya',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заезда'),
        ),
        migrations.AddField(
            model_name='uchastnik',
            name='nuzhen_prozhivanie',
            field=models.BooleanField(default=False, verbose_name='Нужно проживание'),
        ),
        migrations.AddField(
            model_name='uchastnik',
            name='preferencii',
            field=models.TextField(blank=True, help_text='Например: не курящие, тихое место, рядом с другом', verbose_name='Предпочтения'),
        ),
        migrations.AddField(
            model_name='uchastnik',
            name='tip_prozhivaniya',
            field=models.CharField(choices=[('nomer', 'Номер в гостинице'), ('domik', 'Домик на турбазе'), ('palatka', 'Палатка'), ('ne_nuzhno', 'Не нужно')], default='nomer', max_length=50, verbose_name='Тип размещения'),
        ),
    ]
