# Generated by Django 5.1.5 on 2026-02-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_konferentsiya_mesto_provedeniya_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doklad',
            name='file',
            field=models.FileField(blank=True, help_text='Допустимые форматы: PDF, DOC, DOCX, PPT, PPTX (макс. 10MB)', null=True, upload_to='doklads/%Y/%m/%d/', verbose_name='Файл доклада'),
        ),
    ]
