# Generated by Django 5.1.5 on 2026-02-27 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_doklad_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doklad',
            options={'ordering': ['nazvanie']},
        ),
        migrations.RemoveField(
            model_name='doklad',
            name='file',
        ),
        migrations.AddField(
            model_name='doklad',
            name='sektsiya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sekciya', verbose_name='Секция'),
        ),
    ]
