# Generated by Django 5.1.5 on 2026-02-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_doklad_options_remove_doklad_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doklad',
            name='file',
            field=models.FileField(blank=True, help_text='PDF, DOC, DOCX, PPT, PPTX (макс. 10MB)', null=True, upload_to='doklads/%Y/%m/', verbose_name='Файл доклада'),
        ),
    ]
