# Generated by Django 5.1.5 on 2026-03-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_doklad_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='kolvo_transporta',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество машин'),
        ),
    ]
